DROP TABLE IF EXISTS bookings;

CREATE TABLE bookings (
  id IDENTITY PRIMARY KEY,
  trail_id INT NOT NULL,
  date_when DATE NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
